config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: "sessions"}, skip: :registrations
  root "home#index"
  get "tags/:tag", to: "news#index", as: :tag

  namespace :v1 do
    devise_scope :admin do
      post "sign_up", :to => "registrations#create"
      post "sign_in", :to => "sessions#create"
      delete "sign_out", :to => "sessions#destroy"
    end
    resources :news_categories
    resources :feedbacks, only: [:index, :destroy]
    resources :courses
    resources :course_schedules
    resources :users
    resources :newses
    resources :registration_courses
    resources :temporary_registrations, only: [:index, :destroy, :update]
  end

  namespace :admin do
    get "(*all)", to: "courses#index"
  end

  resources :educations, only: :index, path: "quan-ly-dao-tao"
  resources :courses, only: [:index, :show], path: "khoa-hoc"
  resources :feedbacks, only: :create
  get "lien-he", to: "feedbacks#new", as: :new_feedback
  resources :trainers, only: [:show, :index], path: "giang-vien"
  resources :registrations, only: :create
  get "dang-ky-lop-hoc", to: "registrations#new", as: :new_registration
  resources :news, only: [:index, :show], path: "tin-tuc"
  resources :course_schedules, only: [:index, :show], path: "lich-khai-giang"
  resources :temporary_registrations, only: :create
  get "dang-ky-khoa-hoc", to: "temporary_registrations#new", as: :new_temporary_registration

  devise_scope :admin do
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration"
  end
end

app/models/course_schedule.rb
class CourseSchedule < ApplicationRecord
  acts_as_paranoid
  before_save :set_unique_code_schedule, if: ->(obj){obj.new_record? || obj.course_id_changed?}

  has_many :registrations, dependent: :destroy
  belongs_to :course

  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  def slug_candidates
    [:set_slug_string]
  end

  def should_generate_new_friendly_id?
    start_date_changed? || end_date_changed?
  end

  def set_slug_string
    course_name + "-" + I18n.l(start_date, format: :date_month_year_concise) +
      "-" + I18n.l(end_date, format: :date_month_year_concise)
  end

  DAY_OF_WEEK = [:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday]

  validates :start_date, presence: true
  validates :end_date, presence: true

  scope :newest, ->{order start_date: :desc}
  scope :load_by_course, -> course_id{newest.where course_id: course_id}

  delegate :name, to: :course, prefix: true, allow_nil: true
  delegate :cost, to: :course, prefix: true, allow_nil: true
  delegate :technique, to: :course, prefix: true, allow_nil: true
  delegate :category, to: :course, prefix: true, allow_nil: true

  def is_opening?
    self.start_date >= Date.today
  end

  private

  def set_unique_code_schedule
    if last_schedule = CourseSchedule.where(course_id: self.course_id).order(:id).last
      last_code_number = last_schedule.code.scan(/\d+$/).first.to_i
      new_code_number = last_code_number + 1
    else
      new_code_number = 1
    end
    self.code = "#{self.course_technique.downcase}" + "_" + "#{sprintf("%03d", new_code_number)}"
  end
end

app/controllers/course_schedules_controller.rb
class CourseSchedulesController < ApplicationController
  before_action :popular_courses
  before_action :find_schedule, only: :show

  def index
    find_course && return if params[:course]
    @course_schedules = CourseSchedule.newest.page(params[:page])
      .per Settings.course_schedules.per_page
  end

  def show
  end

  private

  def find_schedule
    @course_schedule = CourseSchedule.includes(:course).friendly.find params[:id]
  rescue ActiveRecord::RecordNotFound
    handle_record_not_found
  end

  def find_course
    course = Course.friendly.find params[:course]
    @course_schedules = CourseSchedule.load_by_course(course.id)
      .page(params[:page]).per Settings.course_schedules.per_page
  rescue ActiveRecord::RecordNotFound
    handle_record_not_found
  end
end

app/controllers/v1/course_schedules_controller.rb
class V1::CourseSchedulesController < V1::ApiController
  before_action :load_course_schedule, only: [:destroy, :edit, :update]

  def index
    course_schedules = CourseSchedule.page(page).per Settings.admin_page.per_page
    schedule_serialize = ActiveModel::SerializableResource
      .new(course_schedules, each_serializer: CourseScheduleSerializer)
    response_success nil, {course_schedules: schedule_serialize, page: page,
      pages: course_schedules.total_pages}
  end

  def destroy
    if @course_schedule.destroy
      response_success nil, @course_schedule
    else
      response_error t(".delete_failed"), nil
    end
  end

  def edit
    response_success nil, {course_schedule: @course_schedule, courses: Course.all,
      day_of_week: day_of_week}
  end

  def update
    if @course_schedule.update_attributes(course_schedule_params)
      response_success t(".save_success"), @course_schedule
    else
      response_error t(".save_failed"), @course_schedule.errors.full_messages
    end
  end

  def new
    response_success nil, {courses: Course.all, day_of_week: day_of_week}
  end

  def create
    @course_schedule = CourseSchedule.new course_schedule_params
    if @course_schedule.save
      response_success t(".save_success"), @course_schedule
    else
      response_error t(".save_failed"), @course_schedule.errors.full_messages
    end
  end

  private

  def course_schedule_params
    params.permit :start_date, :end_date, :deadline_date, :course_id, :start_time1,
      :end_time1, :day1, :start_time2, :end_time2, :day2, :start_time3, :end_time3,
      :day3, :place
  end

  def load_course_schedule
    return if @course_schedule = CourseSchedule.find_by(id: params[:id])
    response_not_found t(".not_found"), nil
  end

  def day_of_week
    CourseSchedule::DAY_OF_WEEK.map.with_index do |x, i|
      [i, I18n.t("day_of_week.#{x}")]
    end.to_h
  end
end

app/views/course_schedules/_course_schedule.html.erb
<% course_schedules.each do |schedule| %>
  <tr>
    <td>
      <div class="first-info">
        <%= load_course_image schedule.course, :avatar, "image-w67-h60" %>
        <span class="name"><%= schedule.course_name %></span>
        <span class="label"><%= schedule.course_technique %></span>
      </div>
    </td>
    <td><%= load_register_time schedule %></td>
    <td>
      <ul>
        <%= load_schedule_time_in_list schedule.day1, schedule.start_time1, schedule.end_time1 %>
        <%= load_schedule_time_in_list schedule.day2, schedule.start_time2, schedule.end_time2 %>
        <%= load_schedule_time_in_list schedule.day3, schedule.start_time3, schedule.end_time3 %>
      </ul>
    </td>
    <td>
      <%= appear_cost_schedule schedule.course %>
    </td>
    <td>
      <% if schedule.is_opening? %>
        <%= link_to new_registration_path(schedule: schedule.slug),
          class: "btn-reg", remote: true do %>
          <span><%= t ".register_now" %></span>
        <% end %>
      <% end %>
      <%= link_to course_schedule_path(schedule),
        class: "detail-link" do %>
        <span><%= t ".detail" %></span>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/course_schedules/index.html.erb
<%
  meta_title t(".course_schedules")
  meta_keywords t(".keywords")
  meta_description t(".description")
  meta_author Settings.author
%>
<div id="breadcrumb" class="full-breadcrumb">
  <div class="container">
    <div class="header-page row">
      <div class="title-page col-md-6 col-sm-6">
        <h2><%= t ".course_schedules" %></h2>
      </div>
      <div class="breadcrumbs col-md-6 col-sm-6">
        <ul>
          <li><%= link_to t(".home"), root_path %></li>
          <li class="active"><span><%= t ".course_schedules" %></span></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="main-content" class="full-content">
  <div class="container">
    <div class="row">
      <div id="component" class="col-md-9">
        <div class="opening-time table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th><%= t ".course_name" %></th>
                <th><%= t ".duration" %></th>
                <th><%= t ".schedule_time" %></th>
                <th><%= t ".fee" %></th>
                <th><%= t ".view" %></th>
              </tr>
            </thead>
            <tbody>
              <%= render "course_schedule", course_schedules: @course_schedules %>
            </tbody>
          </table>
          <%= paginate @course_schedules %>
        </div>
      </div>

      <%= render "courses/right_sidebar_course" %>
    </div>
  </div>
</div>

app/views/course_schedules/show.html.erb
<%
  meta_title @course_schedule.course_name
  meta_keywords t(".keywords", technique: @course_schedule.course_technique,
    category: @course_schedule.course_category)
  meta_description t(".description", technique: @course_schedule.course_technique,
    category: @course_schedule.course_category)
  meta_author Settings.author
%>

<div id="breadcrumb" class="full-breadcrumb">
  <div class="container">
    <div class="header-page row">
      <div class="title-page col-md-6 col-sm-6">
        <h2><%= t ".detail_course" %></h2>
      </div>
      <div class="breadcrumbs col-md-6 col-sm-6">
        <ul>
          <li>
            <%= link_to t(".home"), root_path %>
          </li>
          <li>
            <%= link_to t(".schedule"), course_schedules_path %>
          </li>
          <li class="active"><span><%= t ".detail" %></span></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="main-content" class="full-content">
  <div class="container">
    <div class="row">
      <div id="component" class="col-md-9">
        <div class="banner">
          <%= load_course_image @course_schedule.course, :cover, "image-w880-h337" %>
        </div>
        <div class="detail-class">
          <%= render "courses/course_header", course: @course_schedule.course,
            newest_schedule: @course_schedule %>
          <div class="description">
            <%= markdown @course_schedule.course.content %>
          </div>
        </div>
      </div>

      <%= render "courses/right_sidebar_course" %>
    </div>
  </div>
</div>