config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: "sessions"}, skip: :registrations
  root "home#index"
  get "tags/:tag", to: "news#index", as: :tag

  namespace :v1 do
    devise_scope :admin do
      post "sign_up", :to => "registrations#create"
      post "sign_in", :to => "sessions#create"
      delete "sign_out", :to => "sessions#destroy"
    end
    resources :news_categories
    resources :feedbacks, only: [:index, :destroy]
    resources :courses
    resources :course_schedules
    resources :users
    resources :newses
    resources :registration_courses
    resources :temporary_registrations, only: [:index, :destroy, :update]
  end

  namespace :admin do
    get "(*all)", to: "courses#index"
  end

  resources :educations, only: :index, path: "quan-ly-dao-tao"
  resources :courses, only: [:index, :show], path: "khoa-hoc"
  resources :feedbacks, only: :create
  get "lien-he", to: "feedbacks#new", as: :new_feedback
  resources :trainers, only: [:show, :index], path: "giang-vien"
  resources :registrations, only: :create
  get "dang-ky-lop-hoc", to: "registrations#new", as: :new_registration
  resources :news, only: [:index, :show], path: "tin-tuc"
  resources :course_schedules, only: [:index, :show], path: "lich-khai-giang"
  resources :temporary_registrations, only: :create
  get "dang-ky-khoa-hoc", to: "temporary_registrations#new", as: :new_temporary_registration

  devise_scope :admin do
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration"
  end
end

app/views/shared/_latest_news.html.erb
<div class="news">
  <h3><%= t ".latest_news" %></h3>
  <ul>
    <% latest_news.each do |news| %>
      <li>
        <%= link_to news.title, news_path(news) %>
        <span class="date">
          <%= l news.created_at, format: :date_month_year_concise %>
        </span>
      </li>      
    <% end %>
  </ul>
</div>

app/views/shared/_loading.html.erb
<div id="loader-wrapper">
  <div id="loader-container">
    <p id="loadingText"><%= t ".loading" %></p>
  </div>
</div>

app/views/shared/_popular_course.html.erb
<div class="common-class">
  <h3><%= t ".popular_course" %></h3>
  <ul>
    <% popular_courses.each do |popular| %>
      <li>
        <div class="img-class">
          <%= link_to course_path(popular) do %>
            <%= load_course_image popular, :avatar %>
          <% end %>
        </div>
        <div class="info-class">
          <%= link_to popular.name, course_path(popular) %>
          <%= appear_cost popular %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_top_heading.html.erb
<div id="breadcrumb" class="full-breadcrumb">
  <div class="container">
    <div class="header-page row">
      <div class="title-page col-md-6 col-sm-6">
        <h2><%= title %></h2>
      </div>
      <div class="breadcrumbs col-md-6 col-sm-6">
        <ul>
          <li>
            <%= link_to root_path do%>
              <%= t ".home" %>
            <% end %>
          </li>
          <li class="active"><span><%= page_name %></span></li>
        </ul>
      </div>
    </div>
  </div>
</div>