config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: "sessions"}, skip: :registrations
  root "home#index"
  get "tags/:tag", to: "news#index", as: :tag

  namespace :v1 do
    devise_scope :admin do
      post "sign_up", :to => "registrations#create"
      post "sign_in", :to => "sessions#create"
      delete "sign_out", :to => "sessions#destroy"
    end
    resources :news_categories
    resources :feedbacks, only: [:index, :destroy]
    resources :courses
    resources :course_schedules
    resources :users
    resources :newses
    resources :registration_courses
    resources :temporary_registrations, only: [:index, :destroy, :update]
  end

  namespace :admin do
    get "(*all)", to: "courses#index"
  end

  resources :educations, only: :index, path: "quan-ly-dao-tao"
  resources :courses, only: [:index, :show], path: "khoa-hoc"
  resources :feedbacks, only: :create
  get "lien-he", to: "feedbacks#new", as: :new_feedback
  resources :trainers, only: [:show, :index], path: "giang-vien"
  resources :registrations, only: :create
  get "dang-ky-lop-hoc", to: "registrations#new", as: :new_registration
  resources :news, only: [:index, :show], path: "tin-tuc"
  resources :course_schedules, only: [:index, :show], path: "lich-khai-giang"
  resources :temporary_registrations, only: :create
  get "dang-ky-khoa-hoc", to: "temporary_registrations#new", as: :new_temporary_registration

  devise_scope :admin do
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @courses = Course.newest.limit Settings.home.courses_limit
    @trainers = User.trainers.order_to_display.includes(:image)
      .limit Settings.home.trainers_limit
    @course = Course.find_by on_slider_index: true
  end
end

app/views/home/_about_us.html.erb
<div id="bottom-a" class="full-bottom-a">
  <div class="container">
    <div class="about-us">
      <h2 class="title-box"><%= t ".about_us" %></h2>
      <div class="all-about">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#tab-1" data-toggle="tab"><%= t ".our_mission" %></a>
          </li>
          <li role="presentation">
            <a href="#tab-2" data-toggle="tab"><%= t ".our_vision" %></a>
          </li>
          <li role="presentation">
            <a href="#tab-3" data-toggle="tab"><%= t ".core_value" %></a>
          </li>
        </ul>
        <div class="tab-content col-md-6">
          <div role="tabpanel" class="tab-pane active" id="tab-1">
            <p><%= t ".mission_text1" %></p>
            <p><%= t ".mission_text2" %></p>
            <p><%= t ".mission_text3" %></p>
          </div>

          <div role="tabpanel" class="tab-pane" id="tab-2">
            <p><%= t ".vision_text1" %></p>
            <p><%= t ".vision_text1" %></p>
          </div>

          <div role="tabpanel" class="tab-pane" id="tab-3">
            <p><%= t ".core_value_text1" %></p>
            <p><%= t ".core_value_text2" %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_lastest_courses.html.erb
<div id="top-b" class="full-top-b">
  <div class="container">
    <div class="new-class">
      <h2 class="title-box"><%= t ".lastest_courses" %></h2>
      <div class="js-class slide-class list-class">
        <% courses.each do |course| %>
          <div class="i-class">
            <div class="media">
              <%= link_to load_link(course) do %>
                <%= load_course_image course, :avatar, "image-w278-h203" %>
              <% end %>
            </div>
            <div class="info">
              <h3 class="name-class">
                <%= link_to course.name, load_link(course) %>
              </h3>
              <p class="date">
                <%= load_register_time course.newest_schedule %></p>
              <%= appear_cost course %>
              <span class="language"><%= course.technique %></span>
            </div>
          </div>
        <% end %>
      </div>
      <%= link_to courses_path, class: "view-all" do %>
        <%= t ".more" %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_our_clients.html.erb
<div id="bottom-b" class="full-bottom-b">
  <div class="container">
    <div class="partner">
      <h2 class="title-box"><%= t ".our_clients" %></h2>
      <div class="js-partner all-partner">
        <div class="partner-item">
          <img src="media/partner-1.jpg">
        </div>
        <div class="partner-item">
          <img src="media/partner-2.jpg">
        </div>
        <div class="partner-item">
          <img src="media/partner-3.jpg">
        </div>
        <div class="partner-item">
          <img src="media/partner-4.jpg">
        </div>
        <div class="partner-item">
          <img src="media/partner-5.jpg">
        </div>
        <div class="partner-item">
          <img src="media/partner-6.jpg">
        </div>
        <div class="partner-item">
          <img src="media/partner-7.jpg">
        </div>
        <div class="partner-item">
          <img src="media/partner-8.jpg">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_slider.html.erb
<div id="showcase" class="full-showcase">
  <div class="container">
    <div class="row">
      <div class="left-box col-md-8 col-sm-8">
        <div class="js-slide media-slide">
          <div class="item"><a href=""><img alt="<%= t ".faa" %>"
            src="media/banner10.png"></a></div>
          <div class="item"><a href=""><img alt="<%= t ".faa" %>"
            src="media/slide-2.jpg"></a></div>
          <div class="item"><a href=""><img alt="<%= t ".faa" %>"
            src="media/slide-3.jpg"></a></div>
        </div>
      </div>

      <% if course %>
        <div class="right-box col-md-4 col-sm-4">
          <div class="box-info">
            <div class="top-banner">
              <a href="javascript:;"><img alt="<%= t ".faa" %>" src="media/top-banner.jpg"></a>
            </div>
            <div class="top-info">
              <h2>
                <%= link_to load_link course do %>
                  <%= t ".ruby_course" %> <br> (<%= t ".ruby_dev" %>)
                <% end %>
              </h2>
              <p class="time">
                <%= load_register_time course.newest_schedule %></p>
              <%= appear_cost course %>
              <% if course.newest_schedule %>
                <%= link_to new_registration_path(schedule: course.newest_schedule.slug),
                  class: "registration", remote: true do %>
                  <%= t ".register" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_trainers.html.erb
<div id="middle" class="full-midde">
  <div class="container">
    <div class="our-team">
      <h2 class="title-box"><%= t ".trainers" %></h2>
      <p class="desc-box col-md-8 col-md-offset-2"><%= t ".introduce" %></p>
      <div class="all-member">
        <% trainers.each do |trainer| %>
          <%= link_to trainer_path(trainer) do %>
            <div class="member col-md-4 col-sm-6">
              <div class="inbox">
                <div class="unhover-info">
                  <h3 class="name-member"> <%= trainer.name %> <span class="job"><%= trainer.position %> </span></h3>
                  <div class="avatar">
                    <%= image_tag trainer.image.present? ? trainer.image.url : "user_default.jpg" %>
                  </div>
                  <p class="intro"> <%= truncate trainer.quote, length: Settings.home.trainer_quote_limit %></p>
                </div>
                <div class="hover-info">
                  <div class="full-avatar">
                    <%= image_tag trainer.image.present? ? trainer.image.url : "user_default.jpg" %>
                  </div>
                  <h3 class="name"><%= trainer.name %><span class="job"><%= trainer.position %></span></h3>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="view-all-trainers">
      <%= link_to t(".more"), trainers_path %>
    </div>
  </div>
</div>

app/views/home/_who_we_are.html.erb
<div id="top-a" class="full-top-a">
  <div class="container">
    <div class="all-features">
      <h2 class="title-box"><%= t ".who_we_are" %></h2>
      <p class="desc-box col-md-8 col-md-offset-2">
        <%= t ".text" %>
      </p>
      <div class="list-features">
        <div class="item item-1 col-md-3 col-sm-6">
          <div class="content-item">
            <h3><%= t ".agile_title" %></h3>
            <p><%= t ".agile" %></p>
          </div>
        </div>
        <div class="item item-2 col-md-3 col-sm-6">
          <div class="content-item">
            <h3><%= t ".network_title" %></h3>
            <p><%= t ".network" %></p>
          </div>
        </div>
        <div class="item item-3 col-md-3 col-sm-6">
          <div class="content-item">
            <h3><%= t ".certificate_title" %></h3>
            <p><%= t ".certificate" %></p>
          </div>
        </div>
        <div class="item item-4 col-md-3 col-sm-6">
          <div class="content-item">
            <h3><%= t ".teaching_title" %></h3>
            <p><%= t ".teaching" %></p>
          </div>
        </div>
        <div class="item item-5 col-md-3 col-sm-6">
          <div class="content-item">
            <h3><%= t ".expert_title" %></h3>
            <p><%= t ".expert" %></p>
          </div>
        </div>
        <div class="item item-6 col-md-3 col-sm-6">
          <div class="content-item">
            <h3><%= t ".job_title" %></h3>
            <p><%= t ".job" %></p>
          </div>
        </div>
        <div class="item item-7 col-md-3 col-sm-6">
          <div class="content-item">
            <h3><%= t ".sort_skill_title" %></h3>
            <p><%= t ".sort_skill" %></p>
          </div>
        </div>
        <div class="item item-8 col-md-3 col-sm-6">
          <div class="content-item">
            <h3><%= t ".activities_title" %></h3>
            <p><%= t ".activities" %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%
  meta_title t(".index_title")
  meta_keywords t(".keywords")
  meta_description t(".description")
  meta_author Settings.author
%>

<%= render "slider", course: @course %>
<%= render "who_we_are" %>
<%= render "lastest_courses", courses: @courses %>
<%= render "trainers", trainers: @trainers %>
<%= render "about_us" %>
<%= render "our_clients" %>