config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: "sessions"}, skip: :registrations
  root "home#index"
  get "tags/:tag", to: "news#index", as: :tag

  namespace :v1 do
    devise_scope :admin do
      post "sign_up", :to => "registrations#create"
      post "sign_in", :to => "sessions#create"
      delete "sign_out", :to => "sessions#destroy"
    end
    resources :news_categories
    resources :feedbacks, only: [:index, :destroy]
    resources :courses
    resources :course_schedules
    resources :users
    resources :newses
    resources :registration_courses
    resources :temporary_registrations, only: [:index, :destroy, :update]
  end

  namespace :admin do
    get "(*all)", to: "courses#index"
  end

  resources :educations, only: :index, path: "quan-ly-dao-tao"
  resources :courses, only: [:index, :show], path: "khoa-hoc"
  resources :feedbacks, only: :create
  get "lien-he", to: "feedbacks#new", as: :new_feedback
  resources :trainers, only: [:show, :index], path: "giang-vien"
  resources :registrations, only: :create
  get "dang-ky-lop-hoc", to: "registrations#new", as: :new_registration
  resources :news, only: [:index, :show], path: "tin-tuc"
  resources :course_schedules, only: [:index, :show], path: "lich-khai-giang"
  resources :temporary_registrations, only: :create
  get "dang-ky-khoa-hoc", to: "temporary_registrations#new", as: :new_temporary_registration

  devise_scope :admin do
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration"
  end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::BaseController
  def index
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :load_course, only: :show
  before_action :popular_courses

  def index
    @courses = load_by_search_word || load_course_default
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show; end

  private

  def load_course
    @course = Course.includes(:images).friendly.find params[:id]
  rescue ActiveRecord::RecordNotFound
    handle_record_not_found
  end

  def load_course_default
    Kaminari.paginate_array(Course.newest.to_a).page(params[:page])
      .per Settings.courses.per_page
  end

  def load_by_search_word
    Course.by_words(params[:words]).page(params[:page])
      .per Settings.courses.per_page if params[:words]
  end
end

app/controllers/v1/courses_controller.rb
class V1::CoursesController < V1::ApiController
  before_action :load_course, only: [:edit, :update, :destroy]

  def index
    if course_id = params[:on_slider_index]
      Course.transaction do
        Course.update on_slider_index: false
        Course.update course_id, on_slider_index: true
      end
    end
    on_slider_index = Course.find_by(on_slider_index: true).id
    courses = Course.page(page).per Settings.admin_page.per_page
    response_success nil, {courses: courses, page: page,
      on_slider_index: on_slider_index, pages: courses.total_pages}
  end

  def create
    @course = Course.new course_params
    if @course.save
      if params[:avatar].present?
        create_image :avatar
      end
      if params[:cover].present?
        create_image :cover
      end
      response_success t(".save_success"), @course
    else
      response_error t(".save_failed"), @course.errors.full_messages
    end
  end

  def edit
    response_success nil, {course: @course, statuses: Course.statuses.keys,
      avatar: @course.avatar, cover: @course.cover}
  end

  def update
    if params[:avatar].present?
      change_image :avatar
    end
    if params[:cover].present?
      change_image :cover
    end
    if @course.update_attributes course_params
      response_success t(".save_success"), @course
    else
      response_error t(".save_failed"), @course.errors.full_messages
    end
  end

  def destroy
    if @course.destroy
      response_success nil, @course
    else
      response_error t(".delete_failed"), nil
    end
  end

  private

  def course_params
    params.permit :name, :description, :status, :technique, :cost, :content,
      :on_slider_index, :display_cost
  end

  def load_course
    return if @course = Course.find_by(id: params[:id])
    response_not_found t(".not_found"), nil
  end

  def change_image attribute
    if @course.send attribute
      update_image attribute
    else
      create_image attribute
    end
  end

  def update_image attribute
    @course.send(attribute).update_attributes url: params[attribute]
  end

  def create_image attribute
    Image.transaction do
      img = @course.images.create!(url: params[attribute])
      if attribute == :avatar
        @course.update_attributes! avatar_id: img.id
      else
        @course.update_attributes! cover_id: img.id
      end
    end
  end
end

app/views/courses/_course_grid.html.erb
<div class="i-class col-md-4 col-sm-4">
  <div class="media">
    <%= link_to course_path(course) do %>
      <%= load_course_image course, :avatar, "image-w278-h203" %>
    <% end %>
  </div>
  <div class="info">
    <h3 class="name-class">
      <%= link_to course.name, course_path(course) %>
    </h3>
    <p class="date">
      <%= load_register_time course.newest_schedule %>
    </p>
    <%= appear_cost course %>
    <span class="language"><%= course.technique %></span>
  </div>
</div>

app/views/courses/_course_header.html.erb
<h2 class="name-class"><%= course.name.upcase %></h2>
  <div class="full-info">
    <div class="left-col col-md-8 col-sm-8">
      <% if newest_schedule %>
        <div>
          <span class="label-time"><%= t ".time_learn" %></span>
          <%= link_to course_schedules_path(course: course.slug), class: "pull-right" do %>
            <span class="badge"><%= t ".see_more" %></span>
          <% end %>
        </div>
        <div class="datetime">
          <p class="fulltime">
            <i class="fa fa-calendar" aria-hidden="true"></i>
            <%= load_register_time newest_schedule %>
          </p>
          <ul class="detail-time">
            <li>
              <label class="date"><i class="fa fa-clock-o" aria-hidden="true"></i>
                <%= t "day_of_week.#{CourseSchedule::DAY_OF_WEEK[newest_schedule.day1]}" %>
              </label>
              <span class="time">
                <%= load_schedule_time_without_day newest_schedule.start_time1, newest_schedule.end_time1 %>
              </span>
            </li>
            <li>
              <label class="date"><i class="fa fa-clock-o" aria-hidden="true"></i>
                <%= t "day_of_week.#{CourseSchedule::DAY_OF_WEEK[newest_schedule.day2]}" %>
              </label>
              <span class="time">
                <%= load_schedule_time_without_day newest_schedule.start_time2, newest_schedule.end_time2 %>
              </span>
            </li>
            <li>
              <label class="date"><i class="fa fa-clock-o" aria-hidden="true"></i>
                <%= t "day_of_week.#{CourseSchedule::DAY_OF_WEEK[newest_schedule.day3]}" %>
              </label>
              <span class="time">
                <%= load_schedule_time_without_day newest_schedule.start_time3, newest_schedule.end_time3 %>
              </span>
            </li>
          </ul>
          <p class="address">
            <i class="fa fa-map-marker" aria-hidden="true"></i>
            <%= newest_schedule.place %>
          </p>
        </div>
      <% else %>
        <span class="label-time"><%= t ".time_learn" %></span>
        <div class="datetime">
          <div class="comming-soon">
            <h3><%= t ".comming_soon" %></h3>
            <p><%= t ".condition" %></p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="right-col col-md-4 col-sm-4">
      <%= appear_cost course %>
      <%if newest_schedule %>
        <p class="deadline">
          <%= t ".deadline" %>
          <%= l newest_schedule.deadline_date, format: :day_month_year %>
        </p>
        <%= link_to new_registration_path(schedule: newest_schedule.slug),
          class: "btn-registration btn-blue", remote: true do %>
          <%= t ".register_now" %>
        <% end %>
      <% else %>
        <p class="deadline">
          <b><%= number_of_temporary_registration course %></b>
        </p>
        <%= link_to new_temporary_registration_path(course: course.slug),
          class: "btn-registration btn-blue", remote: true do %>
          <%= t ".register_now" %>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/courses/_course_list.html.erb
<div class="view-class">
  <div class="media col-md-4 col-sm-4">
    <%= link_to course_path(course) do %>
      <%= load_course_image course, :avatar, "image-h210" %>
    <% end %>
  </div>
  <div class="info col-md-8 col-sm-8">
    <h3 class="name-class">
      <%= link_to course.name, course_path(course) %>
    </h3>
    <p class="date">
      <%= load_register_time course.newest_schedule %>
    </p>
    <p class="short-desc">
      <%= truncate course.description,
        length: Settings.courses.length_description %>
    </p>
    <div class="bottom-info">
      <%= appear_cost course %>
      <span class="language"><%= course.technique %></span>
    </div>
  </div>
</div>

app/views/courses/_course_schedules.html.erb
<div class="tt-heding type-2">
  <h3 class="tt-heding-title c-h4 txt-uppercase">
    <span><%= t ".schedules" %></span>
  </h3>
</div>
<% course.course_schedules.each do |schedule| %>
  <div class="tt-author course-schedule-container
    <%= set_class_active course_schedule, schedule %>">
    <div class="tt-author-avacell">
      <div class="tt-author-label"><%= t ".duration" %></div>
      <div class="tt-author-tags">
        <div class="schedule-time">
          <p>
            <%= load_schedule_time schedule.day1, schedule.start_time1, schedule.end_time1 %>
          </p>
          <p>
            <%= load_schedule_time schedule.day2, schedule.start_time2, schedule.end_time2 %>
          </p>
          <p>
            <%= load_schedule_time schedule.day3, schedule.start_time3, schedule.end_time3 %>
          </p>
        </div>
      </div>
    </div>
    <div class="tt-author-catcell schedule-duration">
      <%= load_register_time schedule %>
    </div>
    <div class="tt-author-pricecell tt-author-ratecell">
      <div class="tt-author-label"><%= t ".deadline" %></div>
      <div class="tt-author-tags">
        <%= l schedule.deadline_date, format: :day_month_year %>
      </div>
      <div class="tt-author-tags">
        <%= link_to new_registration_path(schedule: schedule.id),
          class: "c-btn type-1 size-2 color-2", remote: true do %>
          <span><%= t ".register_now" %></span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/courses/_right_sidebar.html.erb
<div class="col-md-3">
  <div class="pleft20">
    <div class="empty-space marg-lg-b90 marg-sm-b50 marg-xs-b30"></div>
    <div class="tt-heding type-3">
      <h5 class="tt-heding-title c-h5 txt-uppercase">
        <span><small><%= t ".course_category" %></small></span>
      </h5>
    </div>
    <div class="empty-space marg-lg-b10"></div>
    <%= render "course_categories" %>
    <div class="empty-space marg-lg-b30"></div>
  </div>                    
</div>

app/views/courses/_right_sidebar_course.html.erb
<div id="sidebar" class="rightbar col-md-3">
  <%= render "shared/popular_course", popular_courses: @popular_courses %>
  <%= render "shared/latest_news", latest_news: @latest_news %>
</div>

app/views/courses/index.html.erb
<%
  meta_title t(".all_course")
  meta_keywords t(".keywords")
  meta_description t(".description")
  meta_author Settings.author
%>
<%= render "shared/top_heading", title: t(".all_course"),
  page_name: t(".course") %>
<div id="main-content" class="full-content">
  <div class="container">
    <div class="row">
      <div id="component" class="col-md-9">
        <div class="category-view">
          <div class="search-bar">
            <%= form_tag courses_path, method: "get", multipart: true,
              class: "search-form col-md-9 col-sm-9" do %>
              <div class="search">
                <%= text_field_tag :words, nil, class: "input-text",
                  placeholder: t(".search_course") %>
                <%= submit_tag t(".search"), class: "btn-submit btn-blue" %>
              </div>
            <% end %>
          </div>

          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#grid-layout" data-toggle="tab"><i class="fa fa-th-large" aria-hidden="true"></i></a></li>
            <li role="presentation" class=""><a href="#list-layout" data-toggle="tab"><i class="fa fa-list-ul" aria-hidden="true"></i></a></li>
          </ul>

          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="grid-layout">
              <div class="grid-view list-class row">
                <% @courses.each do |course| %>
                  <%= render "course_grid", course: course %>
                <% end %>
              </div>

            <%= link_to_next_page @courses, t(".load_more"),
              class: "load-more", remote: true %>
            </div>
            <div role="tabpanel" class="tab-pane" id="list-layout">
              <div class="list-view">
                <% @courses.each do |course| %>
                  <%= render "course_list", course: course %>
                <% end %>
              </div>

              <a class="load-more" href="">Xem thêm</a>
            </div>
          </div>
        </div>
      </div>
      <%= render "right_sidebar_course" %>
    </div>
  </div>
</div>

app/views/courses/index.js.erb
<% @courses.each do |course| %>
  $('.grid-view').append("<%= j render(partial: 'course_grid', locals: {course: course}) %>");
  $('.list-view').append("<%= j render(partial: 'course_list', locals: {course: course}) %>");
<% end %>
$('.load-more').replaceWith("<%= escape_javascript(link_to_next_page(@courses, t('.load_more'), \
  remote: true, class: 'load-more'))%>");

app/views/courses/show.html.erb
<%
  meta_title @course.name
  meta_keywords t(".keywords", technique: @course.technique, category: @course.category)
  meta_description t(".description", technique: @course.technique, category: @course.category)
  meta_author Settings.author
%>
<div id="breadcrumb" class="full-breadcrumb">
  <div class="container">
    <div class="header-page row">
      <div class="title-page col-md-6 col-sm-6">
        <h2><%= t ".detail_course" %></h2>
      </div>
      <div class="breadcrumbs col-md-6 col-sm-6">
        <ul>
          <li>
            <%= link_to t(".home"), root_path %>
          </li>
          <li>
            <%= link_to t(".course"), courses_path %>
          </li>
          <li class="active"><span><%= t ".detail_course" %></span></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="main-content" class="full-content">
  <div class="container">
    <div class="row">
      <div id="component" class="col-md-9">
        <div class="banner">
          <%= load_course_image @course, :cover, "image-w880-h337" %>
        </div>
        <div class="detail-class">
          <%= render "course_header", course: @course,
            newest_schedule: @course.newest_schedule %>
          <div class="description">
            <%= markdown @course.content %>
          </div>
        </div>
      </div>

      <%= render "right_sidebar_course" %>
    </div>
  </div>
</div>